services:
  postgres:
    image: postgres:17
    container_name: blockchain-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: explorer
      POSTGRES_PASSWORD: explorer_password
      POSTGRES_DB: blockchain_explorer

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: